### ISSUE TITLE
Hungarian translation ready

### ISSUE THREAD

**Issue by debyos** [ToastHawaii/osm-apps-catalog#94]
Dear All,

I have completed [the Hungarian translation](https://hosted.weblate.org/projects/osm-apps-catalog/-/hu/) of the project. You may now consider to [deploy it](https://osm-apps.zottelig.ch/).
Cheers

_Gábor_

**Comment by ToastHawaii** [comment]
@debyos Thank you very much. That was quick. I took the current status and integrated it into the app: eg. https://osm-apps.zottelig.ch/?lang=hu&category=focus&view=compare
It seems I had to accept a merge request before the whole app became translatable for Hungarian. That's why a part is still open.

**Comment by debyos** [comment]
Thanks for deploying the Hungarian texts.
Meanwhile, I have translated the rest of the catalog (or catalogue), voilá:
https://hosted.weblate.org/projects/osm-apps-catalog/-/hu/

ToastHawaii ***@***.***> ezt írta (időpont: 2024. okt. 12.,
Szo, 16:23):

**Comment by ToastHawaii** [comment]
Thank you. Is published.
